# Generated by Django 4.1.7 on 2023-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_order_items_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Delivered', 'Delivered'), ('Paid', 'Paid')], default='Waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_online',
            field=models.BooleanField(default=False),
        ),
    ]
