# Generated by Django 4.1.7 on 2023-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
